uploads = []
outputs = []

[[generated]]
id = "JMNZNVPG3gdhdmSKfWOvy"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VSM4Eb41pDmxiOgfGwWBu"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "generated_image"
